Repository BaseAdresseNationale/mes-adresses-api, pull requests merged in 2022-04, with the labels that each got.

#320 Correction de la procédure de détection des conflits
  lib/sync/index.js
  package.json
Labels: bug

#324 Modification du code erreur lorsqu'une BAL n'est pas valide lors de la publication
  lib/sync/api-depot.js
Labels: enhancement

#326 Mise à jour @etalab/bal en v2.4.0
  package.json
  yarn.lock
Labels: dependencies

#327 Remplace les messages de validation Joi par ceux du Validateur BAL
  lib/models/__tests__/base-locale.schema.js
  lib/models/__tests__/numero.schema.js
  lib/models/__tests__/toponyme.schema.js
  lib/models/base-locale.js
  lib/models/numero.js
  lib/models/toponyme.js
  lib/models/voie.js
Labels: enhancement
